### ISSUE TITLE
v14 Features & Enhancements

### ISSUE THREAD

**Issue by surajshetty3416** [surajshetty3416/frappe#25]
## V14 specific PRs
(excluding backported PRs)

<details>
<summary>Refactors</summary>

- #15438
- #15436
- #16196
- #17007
- #16817
- #13985
- #16041
- #16840
- #17331
- #17320
- #16871
- #16540
- #16383
- #17419
- #16715
- #17249
- #15786
- #17493
- #14517
- #17134
- #16030
- #16449
- #17159
- #16935
- #17187
- #16200
- #12334
- #15632
- #15639
- #15597
- #15877
- #17417
- #14272
- #16205
- #13861
- #13442
- #13122
- #17389
- #14441
- #17479
- #17254
- #15757
- #16899
- #14457
- #16341
- #16338
- #15411
- #12973
- #16699
- #16886
- #14614
- #14987
- #13753
- #15188
- #15060
- #16527
- #12880
- #16602
- #13307
- #14011
- #14073
- #16932
- #15426
- #16339
- #13506
- #13015
- #16289
- #13057
- #16337
- #15003
- #16511
- #16107
- #14547
- #14913
- #15071
- #14100
- #16139
- #17367
- #13393
- #15221
- #15927
- #13889
- #14530
- #14289
- #16065
</details>

<details>
<summary>Performance</summary>
- #17253
- #16953
- #13173
- #17530
- #16733
- #16549
- #16685
- #17063
- #17061
- #17042
- #15789
- #16823
- #17237
- #16474
- #15976
- #17461
- #17111
- #16424
- #16950
- #16362
- #17431
- #16577
- #16467
- #17153
- #16259
- #16465
- #15398
- #17421
- #16448
- #17107
- #16949
</details>

<details>
<summary>Features</summary>

- #17071
- #16356
- #17006
- #17072
- #17463
- #17012
- #12882
- #17059
- #17276
- #14394
- #16704
- #16653
- #14155
- #14123
- #14179
- #16171
- #17108
- #16274
- #16254
- #15363
- #16130
- #16877
- #15253
- #15335
- #13152
- #14593
- #15515
- #16837
- #15679
- #16195
- #16698
- #16216
- #17003
- #13036
- #17478
- #13954
- #13845
- #13955
- #14380
- #15771
- #15321
- #16238
- #13826
- #17119
- #15516
- #17103
- #14216
- #13746
- #16887
- #14109
- #16712
- #13567
- #15351
- #15538
- #12608
- #15066
- #14998
- #14134
- #12883
- #14978
- #16542
- #13966
- #12784
- #13468
- #15203
- #15964
- #13791
- #13835
- #16364
- #15368
- #16070
- #13528
- #13841
- #16305
- #15237
- #17027
- #16979
- #16186
- #14555
- #16981
- #15355
- #15738
- #13504
- #13579
- #17405
- #16684
- #14108
- #13906
- #15212
- #13868
- #14238
- #15794
- #17021
- #13573
- #16042
- #16591
- #16188
- #16496
- #12847
- #14102
- #17350
- #16187
- #13198
- #13097
- #16478
- #16747
- #16262
- #15220
- #15028
- #14455
- #13333
- #16962
- #16910
- #17259
- #16772
- #13341
- #14281
- #15695
- #12888
- #16278
- #14988
- #14176
</details>

<details>
<summary>CI, build, docs, chore</summary>

- #16790
- #16793
- #16384
- #14360
- #12972
- #12876
- #17362
- #16655
- #13935
- #14085
- #14949
- #17384
- #14105
- #14393
- #17057
- #16012
- #17228
- #17102
- #12961
- #14481
- #14030
- #13768
- #16048
- #17346
- #13720
- #17370
- #17499
- #13161
- #15226
- #12971
- #12926
- #17386
- #16777
- #14364
- #17113
- #14061
- #14269
- #17388
- #15000
- #17212
- #17245
- #16902
- #13790
- #14175
- #13342
- #17303
- #17127
- #13909
- #14270
- #13467
- #16553
- #16493
- #14192
- #13325
- #13621
- #13630
- #13148
- #13405
- #13162
- #17446
- #17248
- #15276
- #15851
- #16948
- #15413
- #16075
- #16285
- #14444
- #16491
- #17051
- #17194
- #13147
- #16202
- #17289
- #16666
- #16854
- #15219
- #13815
- #14868
- #14112
- #17120
- #16283
- #12983
- #17223
- #17038
- #13554
- #13344
- #14958
- #16711
- #17023
- #16890
- #13003
- #14800
- #16423
- #15684
- #16276
- #17271
- #17251
- #15938
- #15685
- #17429
- #17219
- #17221
- #17218
- #17222
- #17252
- #17220
- #17174
- #17355
- #17356
</details>

## Complete list
(including backported PRs)

<details>
<summary>Refactors</summary>

- #15438
- #14173
- #15436
- #16196
- #17007
- #16817
- #13985
- #16041
- #13915
- refactor(minor): move out common functionality from insert and insert_many client functions to a separate function ([#16840](https://github.com/frappe/fr#16840
- #17331
- #17320
- #14271
- #13820
- #16871
- #13102
- #16540
- #16383
- #17419
- #16715
- #17249
- #15786
- #17493
- #14517
- #17134
- #16030
- #16449
- #17159
- #16935
- #17187
- #16200
- #12334
- #15632
- #15639
- #13996
- #15597
- #16773
- #15877
- #17417
- #14272
- #16205
- #13861
- #13697
- #13244
- #13442
- #13122
- #17389
- #13703
- #14441
- #17479
- #17254
- #15757
- #13131
- #16899
- #14457
- #16341
- #16338
- #15411
- #12973
- #16699
- #16886
- #15498
- #14614
- #14987
- #13753
- #13052
- #14499
- #15188
- #15060
- #14888
- #16527
- #12880
- #16602
- #13307
- #14445
- #12997
- #14011
- #14073
- #15095
- #12878
- #15560
- #16932
- #15426
- #16339
- #13506
- #13015
- #16289
- #13057
- #16337
- #15003
- #15120
- #16511
- #16107
- #14547
- #14913
- #15071
- #14100
- #16139
- #17367
- #16363
- #13393
- #15221
- #15927
- #15178
- #13889
- #14530
- #15039
- #14289
- #16065
</details>

<details>
<summary>Performance</summary>

- #17253
- #16953
- #13120
- #13173
- #17530
- #16733
- #16549
- #16685
- #17063
- #17061
- #13785
- #17042
- #13880
- #15789
- #16823
- #17237
- #16199
- #14558
- #16474
- #15976
- #15963
- #17461
- #17111
- #13786
- #12958
- #16334
- #13622
- #15337
- #16424
- #13939
- #13926
- #16950
- #16362
- #17431
- #16577
- #16467
- #17153
- #16259
- #16465
- #15398
- #17421
- #16448
- #17107
- #16949
</details>

<details>
<summary>Features</summary>

- #17071
- #16356
- #17006
- #17072
- #14992
- #17463
- #17012
- #12882
- #17059
- #17276
- #14394
- #16704
- #15103
- #16653
- #16507
- #14155
- #14123
- #13206
- #15915
- #14179
- #15523
- #16171
- #14020
- #13255
- #15709
- #16612
- #16059
- #17108
- #16274
- #12895
- #12999
- #13121
- #16254
- #12966
- #15363
- #16130
- #16877
- #15253
- #13857
- #15335
- #13152
- #14593
- #13760
- #15515
- #14130
- #16837
- #12898
- #15318
- #13575
- #15679
- #16195
- #16698
- #16219
- #16216
- #15703
- #16162
- #17003
- #13036
- #13070
- #17478
- #13954
- #13845
- #16407
- #15379
- #13955
- #14380
- #15771
- #15321
- #16238
- #15502
- #13826
- #17119
- #15516
- #15180
- #17103
- #14216
- #15162
- #13746
- #16887
- #14109
- #16712
- #13567
- #14454
- #14883
- #15351
- #15538
- #14602
- #15248
- #14329
- #12608
- #14388
- #15443
- #15066
- #14998
- #14134
- #12883
- #14978
- #16542
- #16729
- #13966
- #12784
- #13468
- #15203
- #14438
- #14087
- #13823
- #15964
- #13791
- #13320
- #13777
- #14046
- #13835
- #16590
- #16964
- #13676
- #16364
- #14246
- #14305
- #15368
- #13400
- #16070
- #12715
- #15722
- #13855
- #14334
- #13705
- #13528
- #13491
- #14370
- #16605
- #13841
- #14140
- #14513
- #14935
- #16305
- #15237
- #17027
- #16979
- #14226
- #16186
- #16797
- #14555
- #13640
- #12996
- #16981
- #15072
- #15355
- #14159
- #15738
- #15225
- #13504
- #13579
- #17405
- #16684
- #14108
- #14074
- #14358
- #13906
- #15212
- #13868
- #14238
- #15794
- #17021
- #13573
- #16042
- #14419
- #16591
- #14577
- #16188
- #14463
- #16496
- #13395
- #12847
- #16409
- #15918
- #14102
- #17350
- #16187
- #14363
- #13198
- #13097
- #16478
- #16747
- #16257
- #15551
- #16197
- #13165
- #16262
- #13686
- #13056
- #14310
- #13367
- #15220
- #15028
- #14455
- #13333
- #13184
- #16962
- #14879
- #16910
- #14484
- #17259
- #13247
- #16772
- #13341
- #14357
- #14514
- #14281
- #15641
- #15695
- #15835
- #12888
- #15799
- #15102
- #16278
- #14988
- #16543
- #14176
- #14532
- #13707
- #15407
- #15339
</details>

<details>
<summary>Docs, CI, Chore, Build</summary>

- #16790
- #16793
- #16384
- #14360
- #12972
- #13329
- #12876
- #17362
- #16655
- #15968
- #13935
- #13616
- #14085
- #15176
- #14949
- #13030
- #17384
- #14105
- #14393
- #17057
- #16012
- #17228
- #17102
- #12961
- #14481
- #15716
- #14030
- #13768
- #13417
- #16048
- #14550
- #17346
- #13720
- #17370
- #17499
- #13161
- #15226
- #12971
- #12926
- #17386
- #16777
- #14364
- #17113
- #14061
- #14269
- #17388
- #15000
- #17212
- #17245
- #16902
- #13790
- #14175
- #13342
- #17303
- #17127
- #13369
- #15887
- #13539
- #13004
- #13909
- #14270
- #13467
- #16553
- #16493
- #14192
- #13325
- #13621
- #13630
- #13148
- #13405
- #13162
- #17446
- #17248
- #15276
- #13432
- #12896
- #15851
- #16948
- #15413
- #15802
- #16672
- #16075
- #16285
- #16275
- #14444
- #16491
- #17051
- #17194
- #13147
- #16202
- #17289
- #16172
- #16666
- #16003
- #13103
- #16854
- #15219
- #16336
- #13815
- #14868
- #14112
- #17120
- #16283
- #12983
- #17223
- #17054
- #16752
- #17038
- #13554
- #13344
- #14958
- #16711
- #17023
- #14323
- #16890
- #15919
- #13003
- #14800
- #15154
- #15649
- #16647
- #16423
- #15684
- #16276
- #17271
- #17251
- #15938
- #15685
- #17429
- #17219
- #17221
- #17218
- #17222
- #17252
- #17220
- #17174
- #17355
- #17356
- #14956
- #15635
- #14016
</details>

**Comment by barredterra** [comment]
@surajshetty3416 do you also include PRs that have been backported to v13?

**Comment by surajshetty3416** [comment]
> @surajshetty3416 do you also include PRs that have been backported to v13?

Actually, I want to filter them out... but did not really find a good way to do it... not planning to check PRs one-by-one 😅

**Comment by surajshetty3416** [comment]
> Actually, I want to filter them out... but did not really find a good way to do it... not planning to check PRs one-by-one 😅

Updated PR description. Separated backported and non-backported PRs using [this script](https://gist.github.com/surajshetty3416/bb0d084dec760de4c99ae191c6506486).

**Comment by barredterra** [comment]
Another Idea for you script would be to query the GitHub API for any PRs that

1. have `f"(backport {this_pr})"` in the title and
2. have been merged into `version-13-hotfix` or `version-13-pre-release`.

Possibly your script does not work for long PR discussions. https://github.com/frappe/frappe/pull/12715 should match your conditions but is still in the not-backported section.

**Comment by surajshetty3416** [comment]
Updated the script ([link](https://gist.github.com/surajshetty3416/bb0d084dec760de4c99ae191c6506486/revisions#diff-7c71ac6298ad8a6ba2ff415bed5fc4d9c09ec67cadf6ac9c213f844346b7931e)). It now checks for comments.

Also, updated the list.
